import {
  indigo,
  gold,
  gray,
  bronze,
  brown,
  yellow,
  amber,
  orange,
  tomato,
  red,
  blue,
  sky,
  jade,
  slate,
  indigoDarkA,
} from "@radix-ui/colors";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      xs: "350px",
      maxXs: { max: "350px" },
      min380px: "380px",
      max380px: { max: "380px" },
      sm: { min: "500px" },
      maxSm: { max: "499px" },
      md: { min: "668px" },
      maxMd: { max: "667px" },
      lg: { min: "1100px" },
      maxLg: { max: "1099px" },
      min900px: { min: "900px" },
      max900px: { max: "900px" },
      xl: { min: "1440px" },
      maxXl: { max: "1439px" },
    },
    extend: {
      colors: {
        // Radix
        indigo1: indigo.indigo1,
        indigo2: indigo.indigo2,
        indigo3: indigo.indigo3,
        indigo4: indigo.indigo4,
        indigo5: indigo.indigo5,
        indigo6: indigo.indigo6,
        indigo7: indigo.indigo7,
        indigo8: indigo.indigo8,
        indigo9: indigo.indigo9,
        indigo10: indigo.indigo10,
        indigo11: indigo.indigo11,
        indigo12: indigo.indigo12,

        indigoDarkA1: indigoDarkA.indigoA1,
        indigoDarkA2: indigoDarkA.indigoA2,
        indigoDarkA3: indigoDarkA.indigoA3,
        indigoDarkA4: indigoDarkA.indigoA4,
        indigoDarkA5: indigoDarkA.indigoA5,
        indigoDarkA6: indigoDarkA.indigoA6,
        indigoDarkA7: indigoDarkA.indigoA7,
        indigoDarkA8: indigoDarkA.indigoA8,
        indigoDarkA9: indigoDarkA.indigoA9,
        indigoDarkA10: indigoDarkA.indigoA10,
        indigoDarkA11: indigoDarkA.indigoA11,
        indigoDarkA12: indigoDarkA.indigoA12,

        gold1: gold.gold1,
        gold2: gold.gold2,
        gold3: gold.gold3,
        gold4: gold.gold4,
        gold5: gold.gold5,
        gold6: gold.gold6,
        gold7: gold.gold7,
        gold8: gold.gold8,
        gold9: gold.gold9,
        gold10: gold.gold10,
        gold11: gold.gold11,
        gold12: gold.gold12,

        gray1: gray.gray1,
        gray2: gray.gray2,
        gray3: gray.gray3,
        gray4: gray.gray4,
        gray5: gray.gray5,
        gray6: gray.gray6,
        gray7: gray.gray7,
        gray8: gray.gray8,
        gray9: gray.gray9,
        gray10: gray.gray10,
        gray11: gray.gray11,
        gray12: gray.gray12,

        bronze1: bronze.bronze1,
        bronze2: bronze.bronze2,
        bronze3: bronze.bronze3,
        bronze4: bronze.bronze4,
        bronze5: bronze.bronze5,
        bronze6: bronze.bronze6,
        bronze7: bronze.bronze7,
        bronze8: bronze.bronze8,
        bronze9: bronze.bronze9,
        bronze10: bronze.bronze10,
        bronze11: bronze.bronze11,
        bronze12: bronze.bronze12,

        brown1: brown.brown1,
        brown2: brown.brown2,
        brown3: brown.brown3,
        brown4: brown.brown4,
        brown5: brown.brown5,
        brown6: brown.brown6,
        brown7: brown.brown7,
        brown8: brown.brown8,
        brown9: brown.brown9,
        brown10: brown.brown10,
        brown11: brown.brown11,
        brown12: brown.brown12,

        yellow1: yellow.yellow1,
        yellow2: yellow.yellow2,
        yellow3: yellow.yellow3,
        yellow4: yellow.yellow4,
        yellow5: yellow.yellow5,
        yellow6: yellow.yellow6,
        yellow7: yellow.yellow7,
        yellow8: yellow.yellow8,
        yellow9: yellow.yellow9,
        yellow10: yellow.yellow10,
        yellow11: yellow.yellow11,
        yellow12: yellow.yellow12,

        amber1: amber.amber1,
        amber2: amber.amber2,
        amber3: amber.amber3,
        amber4: amber.amber4,
        amber5: amber.amber5,
        amber6: amber.amber6,
        amber7: amber.amber7,
        amber8: amber.amber8,
        amber9: amber.amber9,
        amber10: amber.amber10,
        amber11: amber.amber11,
        amber12: amber.amber12,

        orange1: orange.orange1,
        orange2: orange.orange2,
        orange3: orange.orange3,
        orange4: orange.orange4,
        orange5: orange.orange5,
        orange6: orange.orange6,
        orange7: orange.orange7,
        orange8: orange.orange8,
        orange9: orange.orange9,
        orange10: orange.orange10,
        orange11: orange.orange11,
        orange12: orange.orange12,

        tomato1: tomato.tomato1,
        tomato2: tomato.tomato2,
        tomato3: tomato.tomato3,
        tomato4: tomato.tomato4,
        tomato5: tomato.tomato5,
        tomato6: tomato.tomato6,
        tomato7: tomato.tomato7,
        tomato8: tomato.tomato8,
        tomato9: tomato.tomato9,
        tomato10: tomato.tomato10,
        tomato11: tomato.tomato11,
        tomato12: tomato.tomato12,

        red1: red.red1,
        red2: red.red2,
        red3: red.red3,
        red4: red.red4,
        red5: red.red5,
        red6: red.red6,
        red7: red.red7,
        red8: red.red8,
        red9: red.red9,
        red10: red.red10,
        red11: red.red11,
        red12: red.red12,

        blue1: blue.blue1,
        blue2: blue.blue2,
        blue3: blue.blue3,
        blue4: blue.blue4,
        blue5: blue.blue5,
        blue6: blue.blue6,
        blue7: blue.blue7,
        blue8: blue.blue8,
        blue9: blue.blue9,
        blue10: blue.blue10,
        blue11: blue.blue11,
        blue12: blue.blue12,

        sky1: sky.sky1,
        sky2: sky.sky2,
        sky3: sky.sky3,
        sky4: sky.sky4,
        sky5: sky.sky5,
        sky6: sky.sky6,
        sky7: sky.sky7,
        sky8: sky.sky8,
        sky9: sky.sky9,
        sky10: sky.sky10,
        sky11: sky.sky11,
        sky12: sky.sky12,

        jade1: jade.jade1,
        jade2: jade.jade2,
        jade3: jade.jade3,
        jade4: jade.jade4,
        jade5: jade.jade5,
        jade6: jade.jade6,
        jade7: jade.jade7,
        jade8: jade.jade8,
        jade9: jade.jade9,
        jade10: jade.jade10,
        jade11: jade.jade11,
        jade12: jade.jade12,

        gray1: gray.gray1,
        gray2: gray.gray2,
        gray3: gray.gray3,
        gray4: gray.gray4,
        gray5: gray.gray5,
        gray6: gray.gray6,
        gray7: gray.gray7,
        gray8: gray.gray8,
        gray9: gray.gray9,
        gray10: gray.gray10,
        gray11: gray.gray11,
        gray12: gray.gray12,

        slate1: slate.slate1,
        slate2: slate.slate2,
        slate3: slate.slate3,
        slate4: slate.slate4,
        slate5: slate.slate5,
        slate6: slate.slate6,
        slate7: slate.slate7,
        slate8: slate.slate8,
        slate9: slate.slate9,
        slate10: slate.slate10,
        slate11: slate.slate11,
        slate12: slate.slate12,

        // Primary Colors

        // Secondary Colors

        // Tertiary Colors

        // Danger Colors

        // Warning Colors

        // Success Colors

        // Medium Colors

        // Light Colors
        light: "#F5F5F5",
      },
    },
  },
  plugins: [],
};
