export enum AppFeaturesVisibilityKeysEnum {
	playerDashboard = 'playerDashboard',
	engagerDashboard = 'engagerDashboard',
	adminDashboard = 'adminDashboard',
	users = 'users',
	viewUser = 'viewUser',
	games = 'games',
	gameRooms = 'gameRooms',
	viewGameRoom = 'viewGameRoom',
	topupRequests = 'topupRequests',
	withdrawRequests = 'withdrawRequests',
	inAppNotifications = 'inAppNotifications',
	joinedGameRooms = 'joinedGameRooms',
	joinPrivateGameRoom = 'joinPrivateGameRoom',
	topups = 'topups',
	withdraws = 'withdraws',
	transferCoins = 'transferCoins',
	allTransferCoins = 'allTransferCoins',
	notifications = 'notifications',
	sendNotifications = 'sendNotifications',
	editNotifications = 'editNotifications',
	availableGameRoomsTableInPlayerDashboard = 'availableGameRoomsTableInPlayerDashboard',
	adminDashboardCoinsAppLogs = 'adminDashboardCoinsAppLogs',

	//
	processing = 'processing',
	error = 'error',
	errorMessage = 'errorMessage',
}
