export {
  // Generic Colors
  PRIMARY,
  SECONDARY,
  GREY,
  GREEN,
  RED,
  BLUE,
  PINK,
  YELLOW,
  LIGHT_BROWN,
  DARK_BROWN,
  LIGHT_PURPLE,
  DARK_PURPLE,
  WHITE,
  BLACK,
  // Pre Defined Colors
  TEXT_COLOR,
  LIGHT_TEXT_COLOR,
  DIVIDER_LINE_COLOR,
  CHIP_BG,
  BORDER_COLOR_LIGHT,
} from "./colors";

export {
  // Font Family
  // Rubik Fonts
  FONT_RUBIK_LIGHT,
  FONT_RUBIK_MEDIUM,
  FONT_RUBIK_REGULAR,
  FONT_RUBIK_SEMI_BOLD,
  FONT_RUBIK_BOLD,
  FONT_RUBIK_EXTRA_BOLD,
  FONT_RUBIK_BLACK,
  // Roboto Font
  FONT_ROBOTO_LIGHT,
  FONT_ROBOTO_REGULAR,
  FONT_ROBOTO_MEDIUM,
  FONT_ROBOTO_BOLD,
  FONT_ROBOTO_BLACK,
  // Gilroy Font
  FONT_GILROY_LIGHT,
  FONT_GILROY_REGULAR,
  FONT_GILROY_MEDIUM,
  FONT_GILROY_BOLD,
  FONT_GILROY_EXTRA_BOLD,
  // Hanson Font
  FONT_HANSON_LIGHT,
  FONT_HANSON_BOLD,
  // SFProText Font
  FONT_SFPROTEXT_LIGHT,
  FONT_SFPROTEXT_REGULAR,
  FONT_SFPROTEXT_MEDIUM,
  FONT_SFPROTEXT_SEMI_BOLD,
  FONT_SFPROTEXT_BLACK,
  // Font Weight
  FONT_WEIGHT_LIGHT,
  FONT_WEIGHT_REGULAR,
  FONT_WEIGHT_MEDIUM,
  FONT_WEIGHT_SIME_BOLD,
  FONT_WEIGHT_BOLD,
  FONT_WEIGHT_EXTRA_BOLD,
  // Font Size
  TEXT_SIZE,
  HEADING_SIZE,
  SUB_HEADING_SIZE,
  BTN_TEXT_SIZE,
  SMALL_BTN_TEXT_SIZE,
  HEADER_TITLE_SIZE,
  INPUT_LABEL_SIZE,
  INPUT_TEXT_SIZE,
} from "./fonts";

export { AWS_POOL_ID } from "./keys";
